server:
  port: 0

spring:
  application:
    name: user-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://ai-diary-mysql.mysql.database.azure.com:3306
    username: ${datasource.username}
    password: ${datasource.password}

#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: ${MAIL_ID}
#    password: ${MAIL_PWD}
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false

logging:
  level:
    root: info

eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
