# eureka server port
server:
  port: 8761

# MSA module id (eureka)
spring:
  application:
    name: ai-diary-knou-back

# Eureka server does not need to be included
eureka:
  client:
    register-with-eureka: false  # 레지스트리에 자신을 등록할 것인가 (default : true)
    fetch-registry: false        # 레지스트리에 있는 정보를 가져올 것인가
    service-url: #server의 위치 지정
      defaultZone: http://localhost:8761/eureka

