server:
  port: 8081

client:
  domain: http://localhost:5173

spring:
  application:
    name: user-auth-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://ai-diary-mysql.mysql.database.azure.com:3306/aidiary
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false
  encryptor:
    seed-key: ${SEED_KEY}
  jwt:
    secret-key: ${JWT_KEY}
    expire-time: 10800000 # 3 x 60 x 60 x 1000