spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USER}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
openapi:
  openai:
    key: ${OPEN_AI_KEY}

logging:
  level:
    root: info